haratiapp/api/urls.py
from django.conf.urls import url
from .views import ListProductApi, RetrieveUpdateDeleteProductApi, ListItemAPi

urlpatterns = [
    url(r'^product/$', ListProductApi.as_view(), name = 'listproduct-api'),
    url(r'^product/(?P<pk>\d+)/$', RetrieveUpdateDeleteProductApi.as_view(), name = 'listproduct-api'),
    url(r'^item/$', ListItemAPi.as_view(), name='listitem-api'),

   ]

haratiapp/urls.py
from django.conf.urls import url, include
from .views import AdminIndex, Index, Login, Logout, AdminLogin, Register, Create_Product,List_Product
from .frontend_views import ListProduct


app_name = 'haratiapp'

urlpatterns = [
    #url(r'^$', AdminIndex.as_view(), name = 'adminindex'),

    url(r'^$', Index.as_view(), name = 'index'),


    url(r'^login/$', Login.as_view(), name = 'login'),
    url(r'^logout$', Logout.as_view(), name = 'logout'),
    url(r'^register/$', Register.as_view(), name='register'),



    url(r'^admin-login$', AdminLogin.as_view(), name = 'admin-login'),
    url(r'^admin/createproduct$', Create_Product.as_view(), name='admin_create_product'),
    url(r'^admin/listproduct', List_Product.as_view(), name='admin_list_product'),
    url(r'^listproduct', ListProduct.as_view(), name='listproduct'),


]

haraticollection/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('haratiapp.urls')),
    url(r'^api/', include('haratiapp.api.urls'))

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

haratiapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField

category = (
    ('Clothing','Clothing'), ('FootWear', 'FootWear'), ('Bags&Wallets', 'Bags&Wallets'), ('Accessories', 'Accessories'),
    ('WomenWears','WomenWears')
)


subcategory = (
    ('T-shirt','T-shirt'), ('Casual Shirt', 'Casual Shirt'), ('Half Pants', 'Half Pants'),
    ('Jeans','Jeans'),
    ('Trousers','Trousers'),
    ('Sportswear', 'Sportswear'),
    ('Sweaters', 'Sweaters'),
    ('Boxers', 'Boxers'),
    ('Thermal','Thermal'),
    ('Windcheater','Windcheater')
)


size = (
    ('Double-Extra-Large', 'XXL'),
    ('Extra-Large', 'XL'),
    ('Large', 'L'),
    ('Medium', 'M'),
    ('Small', 'S'),
)
# Create your models here.

quantity = (
    (1, '1'),
    (2, '2'),
    (3,'3'),
    (4,'4'),
    (5,'5'),
    ( 6,'6'),
    (7,'7'),(8,'8'),(9,'9'),(10, '10')
)

color = (
    ('Red','Red'),
    ('Blue', 'Blue'),
    ('Black', 'Black'),
    ('Yellow', 'Yellow'),
    ('White', 'White'),
    ('Green', 'Green')

)

status = (
    (1, 'Yes'),
    (0, 'No')
)

class Time(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False, )
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True, )
    deleted_at = models.DateTimeField(null=True, blank=True)
    class Meta:
        abstract = True

    def delete(self,*args,**kwargs):
        self.deleted_at = timezone.now()
        super().save()


class AboutUs(models.Model):
    address = models.CharField(max_length=100)
    landline_phone= models.CharField(max_length=15)
    mobile_phone = models.CharField(max_length=15)
    email = models.EmailField()

    class Meta:
        verbose_name_plural = "About Us"

    def __str__(self):
        return self.address


################################################# NEW CONCEPT ############################################################



class SubCategory(models.Model):
    category=models.CharField(choices=category, max_length=100)
    subcategory=models.CharField(max_length=100)

    def __str__(self):
        return self.subcategory

class Item(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True,null=True)
    item_number = models.CharField(max_length=25,blank=True,null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, blank=True, null=True)
    size = models.CharField(choices=size, max_length=25,blank=True,null=True)
    color = models.CharField(choices=color, max_length=25,blank=True,null=True)
    price = models.IntegerField(blank=True,null=True)
    status = models.BooleanField(choices=((True,'Publish'),(False,'Dont Publish')), default=False)
    photo = models.ImageField(upload_to='media_cdn', blank=True,null=True)
    def __str__(self):
        return self.name


class Featured(models.Model):
    featured = models.ForeignKey(Item)


class Trending(models.Model):
    trending = models.ForeignKey(Item)

haratiapp/forms.py
from django import forms
from .models import Item

class LoginForm(forms.Form):
    username = forms.CharField(
    widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Email',
        }
    )
    )
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Password',
        }
    ))

class RegisterForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'Enter your username'
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your password'
            }
        )
    )
    repassword = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Re-Enter your password'
            }
        )
    )
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your email'
            }
        )
    )


class AddProduct(forms.ModelForm):
   class Meta:
        model = Item
        fields = ['name', 'description',
                  'item_number', 'size', 'color', 'subcategory', 'price',
                  'status']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter product name',
                'required': 'True',
                            }),
            'description': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter description of your product.',

                            }),
            'item_number': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter item number',

            }),
            'size': forms.Select(attrs={
                'class': 'form-control borderline',
                'placeholder': 'Enter Size',


            }),
             'color': forms.Select(attrs={
                 'class': 'form-control',
                 'placeholder': 'Color',

             }),


            'subcategory': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Subcategory',

            }),

            'price': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Price',

            }),

            'status': forms.Select(attrs={
                'class': 'form-control',
              }),
        }

haratiapp/api/views.py
from rest_framework import generics, mixins
from haratiapp.models import Item
from .serializers import ProductApiSerializer, ItemApiSerializer
from rest_framework import permissions

# class ListProductApi(mixins.CreateModelMixin, generics.ListAPIView):
#     queryset = Prod.objects.all()
#     serializer_class = ProductApiSerializer
#     permission_classes = []
#
#     def post(self, request, *args, **kwargs):
#         return self.create( request, *args, **kwargs)
#
#
#
# class RetrieveUpdateDeleteProductApi(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Prod.objects.all()
#     serializer_class = ProductApiSerializer

class ListProductApi(generics.ListCreateAPIView):
    queryset = Item.objects.all()
    serializer_class = ProductApiSerializer


class RetrieveUpdateDeleteProductApi(generics.RetrieveUpdateDestroyAPIView):
    queryset = Item.objects.all()
    serializer_class = ProductApiSerializer

class ListItemAPi(generics.ListAPIView):
    queryset = Item.objects.all()
    serializer_class = ItemApiSerializer

haratiapp/views.py
from django.views.generic import TemplateView, FormView, ListView
from django.views.generic.edit import CreateView
from .forms import LoginForm, RegisterForm, AddProduct
from django.http import HttpResponseRedirect, HttpResponse
from .mixins import *
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Item
from django.views import View
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from haratiapp.tokens import account_activation_token
from django.core.mail import EmailMessage
from django.urls import reverse



class AdminIndex(EmployeeRequiredMixin, TemplateView):
    template_name = 'haratiapp/dashboard/dashboard.html'


class HomeIndex(EmployeeRequiredMixin ,TemplateView):
    print('home index')
    template_name = 'haratiapp/frontend/homepage.html'


class Index(TemplateView):
    print('just index')
    template_name = 'haratiapp/frontend/homepage.html'


class AdminLogin(TemplateView):
    template_name = 'haratiapp/dashboard/dashboard.html'

class Login(FormView):

    template_name = 'haratiapp/frontend/login.html'
    form_class = LoginForm

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(self.request, user)
            print('User logged in !!')
            if user.is_superuser:
                print('Superuser Detected !!')
                return HttpResponseRedirect('/admin-login')
            print('outside the if')
            return HttpResponseRedirect(reverse('haratiapp:index'))

        else:
            print('An error has occured !!')
            messages.error(self.request, 'Please check your username and password !!')
            return HttpResponseRedirect('/login')



class Logout(EmployeeRequiredMixin, TemplateView):
    def get(self, request):
        logout(request)
        print('user logged out !!')
        return HttpResponseRedirect('/login/')


class Register(FormView):
    template_name = 'haratiapp/dashboard/register.html'
    form_class = RegisterForm

    def form_valid(self, form):
        if form.cleaned_data['password'] == form.cleaned_data['repassword']:
            User.objects.create_user(username = form.cleaned_data['username'], password=form.cleaned_data['password'],
                             email = form.cleaned_data['email'])
        else:
            messages.error(self.request, 'Password do not match!! Please check your passwords and enter again !!')
            return HttpResponseRedirect('/register/')
        return HttpResponseRedirect('/login/')




class Create_Product(CreateView):
    model = Item
    template_name = 'haratiapp/dashboard/create_product.html'
    form_class = AddProduct
    success_url = reverse_lazy('haratiapp:admin_list_product')

    def form_valid(self, form):
        print('here is the key')
        form.save()
        return super().form_valid(form)


class List_Product(ListView):
    model = Item
    template_name = 'haratiapp/dashboard/list_product.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['paginate_by'] = self.paginate_by
        print(self.paginate_by)
        return context

haratiapp/templates/haratiapp/frontend/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link type="text/css" rel="stylesheet" href="{% static 'administration/css/theme-default/bootstrap.css' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'frontend/styles.css' %}">

    <title>HomePage</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'haratiapp:index' %}">haraticollection.com <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fa fa-shopping-basket" style="padding: 0 10px;"></i>Shop</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fa fa-phone" aria-hidden="true" style="padding: 0 10px;"></i>Contact No: 01-4438684</a>
                    </li>



                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
                <ul class="navbar-nav">

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'haratiapp:login' %}"><i class="fa fa-user" style="padding: 0 10px;"></i>Login</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fa fa-shopping-cart" style="padding: 0 10px;"></i>Add to Cart</a>
                    </li>

                </ul>
            </div>
        </nav>

        <div class="logo">
            LOGO HERE
        </div>

        <div id="quickmenu" class="text-center">
            <a href="{% url 'haratiapp:listproduct' %}" style="text-decoration: none; color: black;"><div class="menu1 item shirt dropdown" >Clothing</div></a>
            <a href="{% url 'haratiapp:listproduct' %}" style="text-decoration: none; color: black;"><div class="menu1 item shoes">FootWear</div></a>
            <a href="{% url 'haratiapp:listproduct' %}" style="text-decoration: none; color: black;"><div class="menu2 item t-shirt">Accesories</div></a>
            <a href="{% url 'haratiapp:listproduct' %}" style="text-decoration: none; color: black;"><div class="menu3 item accessories">Bags & Wallets</div></a>
            <a href="{% url 'haratiapp:listproduct' %}" style="text-decoration: none; color: black;"><div class="men4 item accessories">Women's Wear</div></a>
        </div>





    </header>

    {% block content %}
    {% endblock %}

<div class="break" style="margin-top: 5%; margin-bottom: 5%">

</div>


<footer style="border-top:3px solid black;padding: 5%">

           <div class="left">
              <h1 color="#FD7300">Lorem ipsum</h1>
               Lorem ipsum dolor sit amet, consectetur adipisicing elit. At aliquam dolore explicabo perspiciatis maiores! Ullam voluptates aliquid, hic maiores sequi animi laudantium vel eaque voluptas dolores provident ab, id quaerat.
           </div>
           <div class="center">
               <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d510.08086105147964!2d85.31216769967075!3d27.71885933912201!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb18e293ae74bd%3A0x13aa84b1a58b5002!2sHARATI+COLLECTION+CENTER!5e0!3m2!1sen!2snp!4v1537981713861" width="400" height="300" frameborder="0" style="border:0" ></iframe>
           </div>
           <div class="right">
              <h1 color="#FD7300">Lorem ipsum</h1>
               Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, consectetur. Incidunt quasi, et ratione vitae corporis neque delectus ducimus, eveniet in, illo magnam voluptatem unde aut dolorem tempore eius magni.
           </div>

</footer>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'frontend/custom.js' %}"></script>
</body>

</html>

haratiapp/templates/haratiapp/frontend/homepage.html
{% extends 'haratiapp/frontend/base.html' %}
{% block content %}
    <div class="container-fluid" style="background: #ee7600;  margin-top: 40px; padding: 0px;">
        <div class="contents" style="min-height: 250px;">
            <div class="a content-item">
                <div class="e">
                    <img src="/media_cdn/3.jpeg" alt="">
                </div>
                <div class="f" style="color: white;">
                    <h2 style="color: orange">Lorem ipsum </h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat, rerum.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat, rerum.</p>
                </div>
            </div>
            <div class="b content-item">
                <h2 style="background: #ee7600;" class="text-center">News</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex, aspernatur.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, iste.</p>
            </div>
            <div class="c" style="">
            </div>
        </div>
    </div>

    <section id="shop">
        <br><br>
        <div id="choose">
            <div class="featured">Featured</div>
            <div class="latest">Latest</div>
            <div class="trending">Trending</div>
        </div>


        <!-- Start Of Featured Section -->
        <div id="featured-content">
            <div class="featured-content-item">

                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="/media_cdn/shirt4.jpg" style="height: 300px; max-width: 300px;">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                            the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>

            </div>

            <div class="featured-content-item">

                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="/media_cdn/shirt4.jpg" style="height: 300px; max-width: 300px;">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                            the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>

            </div>

            <div class="featured-content-item">

                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="/media_cdn/shirt4.jpg" style="height: 300px; max-width: 300px;">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                            the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>

            </div>

            <div class="featured-content-item">

                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="/media_cdn/shirt4.jpg" style="height: 300px; max-width: 300px;">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                            the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>

            </div>

        </div>

        <!--End of featured Section-->


        <!--Start of latest Section-->
        <div id="latest-content">
            <div class="latest-content-item">

                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="/media_cdn/shirt4.jpg" style="height: 300px; max-width: 300px;">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                            the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>

            </div>

            <div class="latest-content-item">

                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="/media_cdn/shirt4.jpg" style="height: 300px; max-width: 300px;">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                            the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>

            </div>

            <div class="latest-content-item">

                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="/media_cdn/shirt4.jpg" style="height: 300px; max-width: 300px;">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                            the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>

            </div>

            <div class="latest-content-item">

                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="/media_cdn/shirt4.jpg" style="height: 300px; max-width: 300px;">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                            the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>

            </div>

        </div>
        <!--End of latest Section-->

        <!--Start of trending Section-->
        <div id="trending-content">
            <div class="trending-content-item">

                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="/media_cdn/shirt4.jpg" style="height: 300px; max-width: 300px;">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                            the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>

            </div>

            <div class="trending-content-item">

                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="/media_cdn/shirt4.jpg" style="height: 300px; max-width: 300px;">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                            the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>

            </div>

            <div class="trending-content-item">

                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="/media_cdn/shirt4.jpg" style="height: 300px; max-width: 300px;">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                            the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>

            </div>

            <div class="trending-content-item">

                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="/media_cdn/shirt4.jpg" style="height: 300px; max-width: 300px;">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                            the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>

            </div>

        </div>

        <!--End of trending Section-->


    </section>
    <script>
        jQuery(document).ready(function () {
            var x = $("#quickmenu").offset();
            var y = $('#choose').offset();
            jQuery("#quickmenu").wrap('<div class="nav-placeholder"></div>');
            jQuery(".nav-placeholder").height(jQuery("#quickmenu").outerHeight());

            jQuery(window).scroll(function () {
                var scrolltop = jQuery(window).scrollTop();

                if (scrolltop >= x.top && scrolltop <= y.top) {
                    jQuery("#quickmenu").addClass('fixed');
                    jQuery(".item").addClass('reduce');
                } else {
                    jQuery("#quickmenu").removeClass('fixed');
                    jQuery(".item").removeClass('reduce');

                }
            });

            jQuery('#choose .featured').click(function () {
                console.log('shoes clicked !!')
                jQuery('#featured-content').css({
                    'display': 'grid'
                });

                jQuery('#latest-content').css({
                    'display': 'none'
                });
                jQuery('#trending-content').css({
                    'display': 'none'
                });
            });

            jQuery('#choose .latest').click(function () {
                console.log('shoes clicked !!')
                jQuery('#featured-content').css({
                    'display': 'none'
                });

                jQuery('#latest-content').css({
                    'display': 'grid'
                });
                jQuery('#trending-content').css({
                    'display': 'none'
                });
            });

            jQuery('#choose .trending').click(function () {
                console.log('shoes clicked !!')
                jQuery('#featured-content').css({
                    'display': 'none'
                });

                jQuery('#latest-content').css({
                    'display': 'none'
                });
                jQuery('#trending-content').css({
                    'display': 'grid'
                });
            });


        });

    </script>
{% endblock %}

haratiapp/templates/haratiapp/frontend/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">


</head>

<body>
<div class="login">
    <div class="left" style="background-color: orange;">
        asl;dfkjsldflasdf
    </div>
    <div class="center" style="margin-top:10%;">

        <h1>Login</h1>
        {% if messages %}
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        {% endif %}
        <form class="login-form" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <div id="exampleInputEmail1">{{ form.username }}</div>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <div id="exampleInputPassword1">{{ form.password }}</div>
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                    else.
                </small>
            </div>

            <button type="submit" class="btn btn-primary" style="width: 100%">Submit</button>
        </form>

        <a href="{% url 'haratiapp:register' %}">
            <button class="btn btn-success" style="width: 100%; margin-top:2%;">Register</button>
        </a>
        <br>

    </div>
    <div class="right" style="background-color: orange;">
        asdfasdfasdf
    </div>
</div>

</body>
</html>