haratiapp/api/urls.py
from django.conf.urls import url
from .views import ListProductApi, RetrieveUpdateDeleteProductApi, ListItemAPi

urlpatterns = [
    url(r'^product/$', ListProductApi.as_view(), name = 'listproduct-api'),
    url(r'^product/(?P<pk>\d+)/$', RetrieveUpdateDeleteProductApi.as_view(), name = 'listproduct-api'),
    url(r'^item/$', ListItemAPi.as_view(), name='listitem-api'),

   ]

haratiapp/urls.py
from django.conf.urls import url, include
from .views import AdminIndex, Index, Login, Logout, AdminLogin, Register, Create_Product,List_Product
from .frontend_views import ListProduct


app_name = 'haratiapp'

urlpatterns = [
    #url(r'^$', AdminIndex.as_view(), name = 'adminindex'),

    url(r'^$', Index.as_view(), name = 'index'),


    url(r'^login/$', Login.as_view(), name = 'login'),
    url(r'^logout$', Logout.as_view(), name = 'logout'),
    url(r'^register/$', Register.as_view(), name='register'),



    url(r'^admin-login$', AdminLogin.as_view(), name = 'admin-login'),
    url(r'^admin/createproduct$', Create_Product.as_view(), name='admin_create_product'),
    url(r'^admin/listproduct', List_Product.as_view(), name='admin_list_product'),
    url(r'^listproduct', ListProduct.as_view(), name='listproduct'),


]

haraticollection/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('haratiapp.urls')),
    url(r'^api/', include('haratiapp.api.urls'))

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

haratiapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField

category = (
    ('Clothing','Clothing'), ('FootWear', 'FootWear'), ('Bags&Wallets', 'Bags&Wallets'), ('Accessories', 'Accessories'),
    ('WomenWears','WomenWears')
)


subcategory = (
    ('T-shirt','T-shirt'), ('Casual Shirt', 'Casual Shirt'), ('Half Pants', 'Half Pants'),
    ('Jeans','Jeans'),
    ('Trousers','Trousers'),
    ('Sportswear', 'Sportswear'),
    ('Sweaters', 'Sweaters'),
    ('Boxers', 'Boxers'),
    ('Thermal','Thermal'),
    ('Windcheater','Windcheater')
)


size = (
    ('Double-Extra-Large', 'XXL'),
    ('Extra-Large', 'XL'),
    ('Large', 'L'),
    ('Medium', 'M'),
    ('Small', 'S'),
)
# Create your models here.

quantity = (
    (1, '1'),
    (2, '2'),
    (3,'3'),
    (4,'4'),
    (5,'5'),
    ( 6,'6'),
    (7,'7'),(8,'8'),(9,'9'),(10, '10')
)

color = (
    ('Red','Red'),
    ('Blue', 'Blue'),
    ('Black', 'Black'),
    ('Yellow', 'Yellow'),
    ('White', 'White'),
    ('Green', 'Green')

)

status = (
    (1, 'Yes'),
    (0, 'No')
)

class Time(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False, )
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True, )
    deleted_at = models.DateTimeField(null=True, blank=True)
    class Meta:
        abstract = True

    def delete(self,*args,**kwargs):
        self.deleted_at = timezone.now()
        super().save()


class AboutUs(models.Model):
    address = models.CharField(max_length=100)
    landline_phone= models.CharField(max_length=15)
    mobile_phone = models.CharField(max_length=15)
    email = models.EmailField()

    class Meta:
        verbose_name_plural = "About Us"

    def __str__(self):
        return self.address


################################################# NEW CONCEPT ############################################################



class SubCategory(models.Model):
    category=models.CharField(choices=category, max_length=100)
    subcategory=models.CharField(max_length=100)

    def __str__(self):
        return self.subcategory

class Item(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True,null=True)
    item_number = models.CharField(max_length=25,blank=True,null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, blank=True, null=True)
    size = models.CharField(choices=size, max_length=25,blank=True,null=True)
    color = models.CharField(choices=color, max_length=25,blank=True,null=True)
    price = models.IntegerField(blank=True,null=True)
    status = models.BooleanField(choices=((True,'Publish'),(False,'Dont Publish')), default=False)
    photo = models.ImageField(upload_to='media_cdn', blank=True,null=True)
    def __str__(self):
        return self.name


class Featured(models.Model):
    featured = models.ForeignKey(Item)


class Trending(models.Model):
    trending = models.ForeignKey(Item)

haratiapp/forms.py
from django import forms
from .models import Item

class LoginForm(forms.Form):
    username = forms.CharField(
    widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Email',
        }
    )
    )
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Password',
        }
    ))

class RegisterForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'Enter your username'
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your password'
            }
        )
    )
    repassword = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Re-Enter your password'
            }
        )
    )
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your email'
            }
        )
    )


class AddProduct(forms.ModelForm):
   class Meta:
        model = Item
        fields = ['name', 'description',
                  'item_number', 'size', 'color', 'subcategory', 'price',
                  'status']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter product name',
                'required': 'True',
                            }),
            'description': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter description of your product.',

                            }),
            'item_number': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter item number',

            }),
            'size': forms.Select(attrs={
                'class': 'form-control borderline',
                'placeholder': 'Enter Size',


            }),
             'color': forms.Select(attrs={
                 'class': 'form-control',
                 'placeholder': 'Color',

             }),


            'subcategory': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Subcategory',

            }),

            'price': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Price',

            }),

            'status': forms.Select(attrs={
                'class': 'form-control',
              }),
        }

haratiapp/api/views.py
from rest_framework import generics, mixins
from haratiapp.models import Item
from .serializers import ProductApiSerializer, ItemApiSerializer
from rest_framework import permissions

# class ListProductApi(mixins.CreateModelMixin, generics.ListAPIView):
#     queryset = Prod.objects.all()
#     serializer_class = ProductApiSerializer
#     permission_classes = []
#
#     def post(self, request, *args, **kwargs):
#         return self.create( request, *args, **kwargs)
#
#
#
# class RetrieveUpdateDeleteProductApi(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Prod.objects.all()
#     serializer_class = ProductApiSerializer

class ListProductApi(generics.ListCreateAPIView):
    queryset = Item.objects.all()
    serializer_class = ProductApiSerializer


class RetrieveUpdateDeleteProductApi(generics.RetrieveUpdateDestroyAPIView):
    queryset = Item.objects.all()
    serializer_class = ProductApiSerializer

class ListItemAPi(generics.ListAPIView):
    queryset = Item.objects.all()
    serializer_class = ItemApiSerializer

haratiapp/views.py
from django.views.generic import TemplateView, FormView, ListView
from django.views.generic.edit import CreateView
from .forms import LoginForm, RegisterForm, AddProduct
from django.http import HttpResponseRedirect, HttpResponse
from .mixins import *
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Item
from django.views import View
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from haratiapp.tokens import account_activation_token
from django.core.mail import EmailMessage
from django.urls import reverse



class AdminIndex(EmployeeRequiredMixin, TemplateView):
    template_name = 'haratiapp/dashboard/dashboard.html'


class HomeIndex(EmployeeRequiredMixin ,TemplateView):
    print('home index')
    template_name = 'haratiapp/frontend/homepage.html'


class Index(TemplateView):
    print('just index')
    template_name = 'haratiapp/frontend/homepage.html'


class AdminLogin(TemplateView):
    template_name = 'haratiapp/dashboard/dashboard.html'

class Login(FormView):

    template_name = 'haratiapp/frontend/login.html'
    form_class = LoginForm

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(self.request, user)
            print('User logged in !!')
            if user.is_superuser:
                print('Superuser Detected !!')
                return HttpResponseRedirect('/admin-login')
            print('outside the if')
            return HttpResponseRedirect(reverse('haratiapp:index'))

        else:
            print('An error has occured !!')
            messages.error(self.request, 'Please check your username and password !!')
            return HttpResponseRedirect('/login')



class Logout(EmployeeRequiredMixin, TemplateView):
    def get(self, request):
        logout(request)
        print('user logged out !!')
        return HttpResponseRedirect('/login/')


class Register(FormView):
    template_name = 'haratiapp/dashboard/register.html'
    form_class = RegisterForm

    def form_valid(self, form):
        if form.cleaned_data['password'] == form.cleaned_data['repassword']:
            User.objects.create_user(username = form.cleaned_data['username'], password=form.cleaned_data['password'],
                             email = form.cleaned_data['email'])
        else:
            messages.error(self.request, 'Password do not match!! Please check your passwords and enter again !!')
            return HttpResponseRedirect('/register/')
        return HttpResponseRedirect('/login/')




class Create_Product(CreateView):
    model = Item
    template_name = 'haratiapp/dashboard/create_product.html'
    form_class = AddProduct
    success_url = reverse_lazy('haratiapp:admin_list_product')

    def form_valid(self, form):
        print('here is the key')
        form.save()
        return super().form_valid(form)


class List_Product(ListView):
    model = Item
    template_name = 'haratiapp/dashboard/list_product.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['paginate_by'] = self.paginate_by
        print(self.paginate_by)
        return context

haratiapp/templates/haratiapp/dashboard/create_product.html
{% extends 'haratiapp/dashboard/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'styles.css' %}">

</head>
<body>
{% block title %}

    <title>Create Product</title>

{% endblock %}
{% block content %}
    <div class="head">
        <h1 style="text-align: center">Admin Page</h1>

        <a href="{% url 'haratiapp:logout' %}" style="position: relative;float: right; top: -20px;">
            <button class="btn btn-danger">Logout</button>
        </a>
    </div>


    <div class="contents">
        <div class="sidebar">
            <i class="fas fa-align-justify" style="float: right"></i>
            <h1 class="text-center text-bold text">Settings </h1>
            <div class="sidebar-contents">

                <ul>
                    <div class="line"></div>

                        <li>Dashboard Home</li>

                    <div class="line"></div>
                    <li>Logo Management</li>
                    <div class="line"></div>
                    <li>Slider Management</li>
                    <div class="line"></div>
                    <li>Category Management</li>
                    <div class="line"></div>
                    <li>Sub Category Management</li>
                    <div class="line"></div>
                    <a href="{% url 'haratiapp:admin_list_product' %}">
                        <li class="active">Products</li>
                    </a>
                    <div class="line"></div>
                    <li>Add Multiple Pages</li>
                    <div class="line"></div>
                </ul>

            </div>

        </div>
        <div class="main">
            <h1 class="text-center">Add Product</h1>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">

                        <form method="post" action="{% url 'haratiapp:admin_create_product' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name">Name of Product</label>
                                <div id="name">
                                    {{ form.name }}
                                </div>

                            </div>
                            <div class="form-group">
                                <label for="description">Description</label>

                                <div id="description">
                                    {{ form.description }}
                                </div>


                            </div>
                            <div class="form-group">
                                <label for="product_type">Item Number</label>


                                <div id="item_number">
                                    {{ form.item_number }}
                                </div>

                            </div>

                            <div class="form-group">
                                <label for="quantity">Sub Category</label>

                                <div id="subcategory">
                                    {{ form.subcategory }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="productnumber">Size</label>

                                <div id="size">
                                    {{ form.size }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="productnumber">Color</label>

                                <div id="color">
                                    {{ form.color }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="productnumber">Price</label>

                                <div id="price">
                                    {{ form.price }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="productnumber">status</label>

                                <div id="status">
                                    {{ form.status }}
                                </div>
                            </div>


                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>


    <script>
        $("i").click(function () {
            if ($(".sidebar-contents").css('display') == 'none') {
                $(".sidebar-contents").show();
                $("i").css("float", "right");
            } else {
                $(".sidebar-contents").hide();
                $("i").css("float", "left");
                $("i").css("padding-left", "20px");
            }
        });
    </script>
{% endblock %}
</body>


</html>

haratiapp/templates/haratiapp/dashboard/dashboard.html
{% extends 'haratiapp/dashboard/base.html' %}
{% load static %}

{% block title %}
    <title>Dashboard</title>
{% endblock %}

{% block content %}
    <div class="head">
        <h1 style="text-align: center;">Admin Dashboard</h1>
        <a href="{% url 'haratiapp:logout' %}" style="position: relative;float: right; top: -20px;">
            <button class="btn btn-danger">Logout</button>
        </a>
    </div>


    <div class="contents">

        <div class="sidebar">
            <i class="fas fa-align-justify" style="float: right"></i>
            <h1 class="text-center text-bold text">Settings </h1>
            <div class="sidebar-contents">

                <ul>
                    <div class="line"></div>

                        <li class="active">Dashboard Home</li>

                    <div class="line"></div>
                    <li>Logo Management</li>
                    <div class="line"></div>
                    <li>Slider Management</li>
                    <div class="line"></div>
                    <li>Category Management</li>
                    <div class="line"></div>
                    <li>Sub Category Management</li>
                    <div class="line"></div>
                    <a href="{% url 'haratiapp:admin_list_product' %}">
                        <li>Products</li>
                    </a>
                    <div class="line"></div>
                    <li>Add Multiple Pages</li>
                    <div class="line"></div>
                </ul>

            </div>

        </div>

        <div class="main">
            <h1 class="text-center">Dashboard</h1>
            <div class="line"></div>
        </div>

    </div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    <script>
        $("i").click(function () {
            if ($(".sidebar-contents").css('display') == 'none') {
                $(".sidebar-contents").show();
                $("i").css("float", "right");
            } else {
                $(".sidebar-contents").hide();
                $("i").css("float", "left");
                $("i").css("padding-left", "20px");
            }
        });
    </script>
{% endblock %}
</body>


</html>

haratiapp/templates/haratiapp/dashboard/home.html
{% extends 'haratiapp/dashboard/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">

</head>
<body>
{% block content %}
    <div class="head">
        <h1 style="text-align: center">Home Page</h1>
        <a href="{% url 'haratiapp:logout' %}" style="position: relative;float: right; top: -20px;">
            <button class="btn btn-danger">Logout</button>
        </a>
    </div>


    <div class="contents">
        <div class="sidebar">
            <i class="fas fa-align-justify" style="float: right"></i>
            <h1 class="text-center text-bold text">Settings </h1>
            <div class="sidebar-contents">

                <ul>
                    <div class="line"></div>
                    <li class="active">Home</li>
                    <div class="line"></div>
                    <li>Logo Management</li>
                    <div class="line"></div>
                    <li>Slider Management</li>
                    <div class="line"></div>
                    <li>Category Management</li>
                    <div class="line"></div>
                    <li>Sub Category Management</li>
                    <div class="line"></div>
                    <li>Add Product</li>
                    <div class="line"></div>
                    <li>Add Multiple Pages</li>
                    <div class="line"></div>
                </ul>

            </div>

        </div>
        <div class="main">
            <h1>Home</h1>
        </div>

    </div>


    <script>
        $("i").click(function () {
            if ($(".sidebar-contents").css('display') == 'none') {
                $(".sidebar-contents").show();
                $("i").css("float", "right");
            } else {
                $(".sidebar-contents").hide();
                $("i").css("float", "left");
                $("i").css("padding-left", "20px");
            }
        });
    </script>
{% endblock %}
</body>


</html>

haratiapp/templates/haratiapp/dashboard/list_product.html
{% extends 'haratiapp/dashboard/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">

</head>
<body>
{% block title %}

    <title>List Product</title>

{% endblock %}

{% block content %}

    <div class="head">
        <h1 style="text-align: center">Admin Dashboard</h1>
        <a href="{% url 'haratiapp:logout' %}">
            <button class="btn btn-danger" style="position: relative;float: right; top: -20px;">Logout</button>
        </a>
        <a href="{% url 'haratiapp:index' %}" style="position: relative;float: right; top: -20px;">
            <button class="btn btn-info">Go to Homepage</button>
        </a>
        <a href="{% url 'haratiapp:admin_create_product' %}">
            <button class="btn btn-primary" style="position: relative;float: right; top: -20px;">Add Products</button>
        </a>


    </div>


    <div class="contents">
        <div class="sidebar">
            <i class="fas fa-align-justify" style="float: right"></i>
            <h1 class="text-center text-bold text">Settings </h1>
            <div class="sidebar-contents">

                <ul>
                    <div class="line"></div>

                        <li>Dashboard Home</li>

                    <div class="line"></div>
                    <li>Logo Management</li>
                    <div class="line"></div>
                    <li>Slider Management</li>
                    <div class="line"></div>
                    <li>Category Management</li>
                    <div class="line"></div>
                    <li>Sub Category Management</li>
                    <div class="line"></div>
                    <a href="{% url 'haratiapp:admin_list_product' %}">
                        <li class="active">Products</li>
                    </a>
                    <div class="line"></div>
                    <li>Add Multiple Pages</li>
                    <div class="line"></div>
                </ul>

            </div>

        </div>
        <div class="main">
            <h1 class="text-center">List of Products</h1>
            <div class="line"></div>
            <input type="text" name="search" placeholder="Search.." class="search">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">

                        <table style="width:100%" border="1">
                            <tr>
                                <th>Name</th>
                                <th>Description</th>
                                <th>ItemNumber</th>
                                <th>Category</th>
                                <th>SubCategory</th>
                                <th>Size</th>
                                <th>Color</th>
                                <th>Price</th>
                                <th>Publish Status</th>
                            </tr>
                            {% for obj in object_list %}
                                <tr>

                                    <td>{{ obj.name }}</td>
                                    <td>{{ obj.description }}</td>
                                    <td>{{ obj.item_number }}</td>
                                    <td>{{ obj.category }}</td>
                                    <td>{{ obj.subcategory }}</td>
                                    <td>{{ obj.size }}</td>
                                    <td>{{ obj.color }}</td>
                                    <td>{{ obj.price }}</td>
                                    <td>{{ obj.status }}</td>


                                </tr>
                            {% endfor %}
                        </table>


                        {% if is_paginated %}



                            <ul class="pagination">

                                {% if page_obj.has_previous %}
                                    <li>
                                        <a href="?paginate_by={{ paginate_by }}&page={{ page_obj.previous_page_number }}"><i
                                                class="fa fa-chevron-left"
                                                aria-hidden="true"></i></a></li>
                                {% else %}
                                    <li class="disabled"><span><i class="fa fa-chevron-left"
                                                                  aria-hidden="true"></i></span></li>
                                {% endif %}

                                {% if page_obj.number|add:'-4' > 1 %}
                                    <li><a href="?paginate_by={{ paginate_by }}&page={{ page_obj.number|add:'-5' }}">&hellip;</a>
                                    </li>
                                {% endif %}

                                {% for i in page_obj.paginator.page_range %}

                                    {% if page_obj.number == i %}
                                        <li class="active"><span>{{ i }} <span
                                                class="sr-only">(current)</span></span>
                                        </li>
                                    {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                                        <li><a href="?paginate_by={{ paginate_by }}&page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}

                                {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                                    <li><a href="?paginate_by={{ paginate_by }}&page={{ page_obj.number|add:'5' }}">&hellip;</a>
                                    </li>
                                {% endif %}

                                {% if page_obj.has_next %}
                                    <li><a href="?paginate_by={{ paginate_by }}&page={{ page_obj.next_page_number }}"><i
                                            class="fa fa-chevron-right"
                                            aria-hidden="true"></i></a></li>
                                {% else %}
                                    <li class="disabled"><span><i class="fa fa-chevron-right"
                                                                  aria-hidden="true"></i></span></li>
                                {% endif %}
                            </ul>


                        {% endif %}

                    </div>
                </div>
            </div>

        </div>

    </div>

    <style>
        td {
            padding: 20px;
        }

        input[type=text] {
            width: 130px;
            -webkit-transition: width 0.4s ease-in-out;
            transition: width 0.4s ease-in-out;
        }

        /* When the input field gets focus, change its width to 100% */
        input[type=text]:focus {
            width: 96%;

        }

        .search {
            margin: 20px;
        }

    </style>
    <script>
        $("i").click(function () {
            if ($(".sidebar-contents").css('display') == 'none') {
                $(".sidebar-contents").show();
                $("i").css("float", "right");
            } else {
                $(".sidebar-contents").hide();
                $("i").css("float", "left");
                $("i").css("padding-left", "20px");
            }
        });
    </script>
{% endblock %}
</body>


</html>